sudo: required
language: generic

services:
  - docker

script:
  - wget -O- https://raw.githubusercontent.com/petzah/travis.debian.net/non-greedy/script.sh | sh -

branches:
  except:
    - /^debian\/\d/
